@startuml

message "*" --> "1" conversation : sent >

conversationRepo <-- listener 
authorization .. (conversationRepo, listener)

conversationRepo --> "*" listener : forwards \nmessage
(conversationRepo, listener) .. authorization
listener "1" <|-- "1" user
listener "1" <|- "1" participant : joins <

conversation "*" - "1" conversationRepo

message : idNumber[]
message : contents[]

authorization : authorizeFwd()
authorization : authorizeListener()

conversation : idNumber[]
conversation : fwdMsg()

listener : userId[]


@enduml