@startuml




[*] -> joinConversation:authorizeUser

joinConversation --> receiveConversation:authorizeConversation

receiveConversation -> listenToMessage:receiveForwardedMessages

listenToMessage --> [*]


@enduml